name: Publish artifact

on:
  release:
    types: [published]

jobs:
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      project-version: ${{ steps.set-version.outputs.project-version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set version
        id: set-version
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "::set-output name=project-version::$version"
  war:
    runs-on: ubuntu-latest
    needs: determine-version
    steps:
      - name: Fetch war
        id: fetch-war
        run: |
          FILE_NAME=jenkins.war
          PROJECT_VERSION=${{ needs.determine-version.outputs.project-version }}
          echo $PROJECT_VERSION
          echo "::set-output name=file-name::$FILE_NAME"
          wget -q https://get.jenkins.io/war/${PROJECT_VERSION}/jenkins.war
      - name: Upload Release Asset
        id: upload-war
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.fetch-war.outputs.file-name }}
          asset_name: ${{ steps.fetch-war.outputs.file-name }}
          asset_content_type: application/java-archive
  debian:
    runs-on: ubuntu-latest
    needs: determine-version
    steps:
      - name: Fetch Deb
        id: fetch-deb
        if: always()
        run: |
          PROJECT_VERSION=${{ needs.determine-version.outputs.project-version }}
          echo $PROJECT_VERSION
          FILE_NAME=jenkins_${PROJECT_VERSION}_all.deb
          echo "::set-output name=file-name::$FILE_NAME"
          wget -q https://get.jenkins.io/debian/${FILE_NAME}
      - name: Upload Release Asset
        id: upload-deb
        if: always()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.fetch-deb.outputs.file-name }}
          asset_name: ${{ steps.fetch-deb.outputs.file-name }}
          asset_content_type: application/vnd.debian.binary-package
  redhat:
    runs-on: ubuntu-latest
    needs: determine-version
    steps:
      - name: Fetch RPM
        id: fetch-rpm
        if: always()
        run: |
          PROJECT_VERSION=${{ needs.determine-version.outputs.project-version }}
          echo $PROJECT_VERSION
          FILE_NAME=jenkins-${PROJECT_VERSION}-1.1.noarch.rpm
          echo "::set-output name=file-name::$FILE_NAME"
          wget -q https://get.jenkins.io/redhat/${FILE_NAME}
      - name: Upload Release Asset
        id: upload-rpm
        if: always()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.fetch-rpm.outputs.file-name }}
          asset_name: ${{ steps.fetch-rpm.outputs.file-name }}
          asset_content_type: application/x-redhat-package-manager
  windows:
    runs-on: ubuntu-latest
    needs: determine-version
    steps:
      - name: Fetch MSI
        id: fetch-msi
        if: always()
        run: |
          PROJECT_VERSION=${{ needs.determine-version.outputs.project-version }}
          echo $PROJECT_VERSION
          FILE_NAME=jenkins.msi
          echo "::set-output name=file-name::$FILE_NAME"
          wget -q https://get.jenkins.io/windows/${PROJECT_VERSION}/jenkins.msi
      - name: Upload Release Asset
        id: upload-msi
        if: always()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.fetch-msi.outputs.file-name }}
          asset_name: ${{ steps.fetch-msi.outputs.file-name }}
          asset_content_type: application/octet-stream
  suse:
    runs-on: ubuntu-latest
    needs: determine-version
    steps:
      - name: Fetch suse rpm
        id: fetch-suse-rpm
        if: always()
        run: |
          PROJECT_VERSION=${{ needs.determine-version.outputs.project-version }}
          echo $PROJECT_VERSION
          FILE_NAME=jenkins-${PROJECT_VERSION}-1.2-opensuse.noarch.rpm
          echo "::set-output name=file-name::$FILE_NAME"
          wget -q https://get.jenkins.io/opensuse/jenkins-${PROJECT_VERSION}-1.2.noarch.rpm -O ${FILE_NAME} 
      - name: Upload Release Asset
        id: upload-suse-rpm
        if: always()
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.fetch-suse-rpm.outputs.file-name }}
          asset_name: ${{ steps.fetch-suse-rpm.outputs.file-name }}
          asset_content_type: application/x-redhat-package-manager
